### ISSUE TITLE
Special formatting of text does not work on web

### ISSUE THREAD

**Issue by ifiok** [Chieze-Franklin/jamb-bot#1]
<img width="261" alt="screen shot 2017-07-16 at 6 43 32 pm" src="https://user-images.githubusercontent.com/8256305/28249922-c1ed1ece-6a56-11e7-92ea-c56ae48cc9a6.png">

Special formatting of text does not work on the web. Possibly find an alternative for the web version.

**Comment by Chieze-Franklin** [comment]
Good morning Ifiok Idiang,

Thanks very much for the feed back. I hope to be able to find how to
represent italics on the Facebook Messenger platform (It is an issue with
Facebook Messenger not web). Until then I am constrained to using asterisks
(**).

Thanks once again,
Frank.

**Comment by ifiok** [comment]
Okay. I noticed that as well. I guess there's a grammatical error then. In the question instructions, it should be **asterisks** then, instead of _italics_.

**Comment by Chieze-Franklin** [comment]
Thanks once again for the feedback. The 'italics' is what obtains on the
actual JAMB paper. The '(**)' is my addition to help people know what
portion of the questions are supposed to be in italics.

If, however, I do get more feedbacks on this issue I will make the
necessary changes.

Thanks again. I feel honoured and pleasantly surprised that a piece of
software I created as a playful side project is being tried out by people.
